### ISSUE TITLE
Issue on Recommendations- Wrong parameter is used on API call to Insight

### ISSUE THREAD

**Issue by MineOgre** [openmaker-eu/dsp-explorer#4]
Hi,
We noticed that you are calling Insight API for **recommending News and Events** as follows: 

http://178.62.229.16:8484/api/v1.0/recommendation/news?api_key=APIKEY&page=1&crm_id=174704399

However, as documented at [http://178.62.229.16:8484/api/v1.1#personalized-recommendations]

The call should be as follows: 
http://178.62.229.16:8484/api/v1.0/recommendation/news?api_key=APIKEY&page=1&crm_ids=[174704399]

There is no parameter as "crm_id", so that **all the news and events are retrieved regardless of the logged in user**.

**Comment by santoli-massimo** [comment]
Closed
